### ISSUE TITLE
Hosted control planes ( HCP ) topology

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#109]
ROSA already offers clusters in the "classic" OpenShift topology where control-plane and workers are all in the customer's AWS account.

This new topology, Hosted control planes (HCP), puts the control plane in the Red Hat AWS account, and the workers in the customer's AWS account. The result is infrastructure cost savings as well as manageability improvements.

**Comment by bhavikbhavsar** [comment]
Hi @arendej, I am looking for a terraform provider to create a rosa with hosted control plane.. do we have this created some place. or can you guide me to where I can look for?

**Comment by bchandra-ocp** [comment]
https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html#rosa-hcp-classic-comparison_rosa-hcp-sts-creating-a-cluster-quickly
