### ISSUE TITLE
day2 PodPidsLimit (Kubelet) configuration

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#115]
Ability for configuring KubeletConfig parameter PodPidsLimit to define/increase maximum Process IDs per Pod for all pods in the node.

**Comment by bchandra-ocp** [comment]
https://github.com/openshift/rosa/releases/tag/v1.2.31

Enable modification of cluster PIDs limit: rosa create kubeletconfig -c $CLUSTER_ID --pod-pids-limit=$PID_LIMIT.
Enable modification of cluster PIDs limit: rosa describe kubeletconfig -c $CLUSTER_ID.
Enable modification of cluster PIDs limit: rosa edit kubeletconfig -c $CLUSTER_ID --pod-pids-limit=$PID_LIMIT.
Enable modification of cluster PIDs limit: rosa delete kubeletconfig -c $CLUSTER_ID.

**Comment by bchandra-ocp** [comment]
follow what's new in our ROSA documentation
https://docs.openshift.com/rosa/rosa_release_notes/rosa-release-notes.html
