### ISSUE TITLE
day1 security groups

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#117]
Ability for customers to specify AWS Security Groups (SGs) for cluster worker nodes during cluster creation.

**Comment by bchandra-ocp** [comment]
Released in ROSA CLI v.1.2.31
https://github.com/openshift/rosa/releases/tag/v1.2.31

Product Documentation:

https://docs.openshift.com/rosa/cli_reference/rosa_cli/rosa-manage-objects-cli.html#rosa-create-cluster-command_rosa-managing-objects-cli
