### ISSUE TITLE
day2 security groups

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#118]
Ability for customers to specify AWS Security Groups while creating new machine pools in an existing cluster

**Comment by bchandra-ocp** [comment]
https://docs.openshift.com/rosa/cli_reference/rosa_cli/rosa-manage-objects-cli.html#rosa-create-cluster-command_rosa-managing-objects-cli 

https://github.com/openshift/rosa/releases/tag/v1.2.28
