### ISSUE TITLE
ROSA(4.14) needs support for 7th generation general purpose (m7i), memory optimized(r7i) and compute optimized instance types(c7i) 

### ISSUE THREAD

**Issue by maulik-modi22** [openshift-cs/managed-openshift#134]
**Which service is this feature request for?**
 Red Hat OpenShift Service on AWS

**What are you trying to do?**
Provision cluster utilising [M7i](https://aws.amazon.com/ec2/instance-types/m7i/) or [r7i](https://aws.amazon.com/blogs/aws/new-seventh-generation-memory-optimized-amazon-ec2-instances-r7i/) or [c7i](https://aws.amazon.com/ec2/instance-types/c7i/) instance types for worker, infrastructure or master nodes

**Describe the solution you'd like**
[Test OCP 4.14 against m7i, r7i, c7i instance types and update documentation including them as tested instance types
](https://docs.openshift.com/container-platform/4.14/installing/installing_aws/installing-aws-customizations.html)

**Describe alternatives you've considered**
Can customers claim support when they use M7i, r7i, c7i instance types in ROSA as worker, master or infrastructure nodes?

**Additional context**
Customer will get to leverage latest Intel Xeon 4th generation processors and get better price/performance

**Comment by arendej** [comment]
These are on the way for ROSA worker nodes.

**Comment by maulik-modi22** [comment]
@arendej , Can you please link it with any other existing issue already under Development or assign a milestone?

**Comment by maulik-modi22** [comment]
#119

**Comment by maulik-modi22** [comment]
@arendej , I guess this is ready to be closed unless you see something is pending.

**Comment by maulik-modi22** [comment]
@arendej, @wgordon17, Kindly close this issue, I can see these instance types available on https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-instance-types.html
