### ISSUE TITLE
ROSA w/ HCP: scale to 500 node clusters

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#148]
ROSA w/ HCP: scale to 500 node clusters

Safely support clusters with up to 500 nodes as validated by Red Hat load testing.

**Comment by bchandra-ocp** [comment]
https://docs.openshift.com/rosa/rosa_planning/rosa-hcp-limits-scalability.html#tested-cluster-maximums-hcp-sd_rosa-hcp-limits-scalability
