### ISSUE TITLE
Add support for ALB Load balancers

### ISSUE THREAD

**Issue by acathrow** [openshift-cs/managed-openshift#17]
Add support for ALB Load balancers in addition to network load balancers .

**Comment by mreinli** [comment]
Can you provide some indication when this will become available for ROSA?

**Comment by acathrow** [comment]
This is now fully supported with OCP 4.11 and 4.12

**Comment by bchandra-ocp** [comment]
https://docs.openshift.com/rosa/networking/aws-load-balancer-operator.html
