### ISSUE TITLE
Support for OCS/ODF

### ISSUE THREAD

**Issue by 0kashi** [openshift-cs/managed-openshift#20]
Currently OpenShift Storage / OpenShift Data Foundation cannot be installed into a ROSA or OSA cluster due to service restrictions (namespace and node labels). These restrictions will are being addressed to allow installation of OCS/ODF managed by the cluster owner.

**Comment by walidshaari** [comment]
if it is completed and GA why issue still open?

**Comment by GabLeme** [comment]
is possible to install ODF now?
