### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by acathrow** [openshift-cs/managed-openshift#4]
A Terraform provider for ROSA, fully featured.
This is in progress ~and the upstream work can be tracked here: https://github.com/openshift-online/terraform-provider-ocm~

The Terraform content for this has been released 
 here: [https://github.com/terraform-redhat/terraform-provider-rhcs](https://github.com/terraform-redhat/terraform-provider-rhcs)

ROSA (Classic) can be provisioned and managed with Terraform. Feature parity efforts will be ongoing with Terraform now considered an official client.

**Comment by arcgang** [comment]
This feature will be a game-changer for customers who are managing all of their AWS services through IaC. Is there a way to get an early preview of the terraform module?

**Comment by robbytherobotibm** [comment]
is there any eta on this?

**Comment by arendej** [comment]
to quote the developer:

> the provider is currently 0.1 to indicate that it is at very early stage of development. The functionality isn't complete and there is no backwards compatibility guarantee

It's much too early for public consumption, but it's there in skeletal form, and it will be great.
No ETA at this time.

**Comment by arendej** [comment]
to quote the developer:

> the provider is currently 0.1 to indicate that it is at very early stage of development. The functionality isn't complete and there is no backwards compatibility guarantee

It's much too early for public consumption, but it's there in skeletal form, and it will be great.
No ETA at this time.

**Comment by cirego** [comment]
:+1: This would be super useful for creating temporary clusters when certifying projects on top of OpenShift.

**Comment by cloudbustinguk** [comment]
This is the biggest ask at one of my customers, and almost a blocker to OpenShift adoption. Looking forward to getting this.

**Comment by tabnul** [comment]
IAC is the industry standard in 2022. No IAC is a blocker for most companies i know. For good reasons.
What is the status of the provider?

**Comment by acathrow** [comment]
@tabnul it is under active development but is functional today I just added a link to the upstream project in the description.
You should be able to use this today and we would welcome input, feedback, in the upstream project
https://github.com/openshift-online/terraform-provider-ocm
