### ISSUE TITLE
[New Feature Request] Alerts for monitoring workloads in user-defined projects

### ISSUE THREAD

**Issue by mosuke5** [openshift-cs/managed-openshift#41]
**For which service is this feature request for?**
Red Hat OpenShift Service on AWS

**What are you trying to do?**
I am trying to configure an alert receiver in Alertmanager, but the configuration does not apply.
Currently, alerts for monitoring user-defined project workloads are not supported [1].

[1] https://docs.openshift.com/rosa/monitoring/osd-managing-alerts.html

**Please describe the solution you want**.
I want to configure alerts to monitor the workload of user-defined projects.

**Describe alternatives you've considered**.
The inability to configure alerts is critical for production environment.
Therefore, I'm considering using Prometheus Operator and managing Prometheus on my own.

**Comment by wgordon17** [comment]
Hi @mosuke5, thank you for reporting this RFE. We're currently tracking this on OpenShift Container Platform in https://issues.redhat.com/browse/OBSDA-3.

**Comment by mosuke5** [comment]
@wgordon17 thank you for your reply and adding to backlog. I'll track the issue.

**Comment by wgordon17** [comment]
This feature is live and available to all clusters 4.11+
