### ISSUE TITLE
ROSA CLI command to list / delete IAM resources

### ISSUE THREAD

**Issue by acathrow** [openshift-cs/managed-openshift#43]
Add command to list and delete account-roles, operator-roles and oidc providers

eg. 
rosa list operator-roles
rosa list oidc-providers
rosa list account-roles

rosa delete operator-roles
rosa delete oidc-providers
rosa delete account-roles

**Comment by arendej** [comment]
list operator roles
and
list oidc-provider

Are still in the works.
