### ISSUE TITLE
STS support for cloud forwarding

### ISSUE THREAD

**Issue by 0kashi** [openshift-cs/managed-openshift#56]
Enable ROSA STS clusters to use the log forwarding operator.  Currently it is limited due to permissions limitations but a temporary workaround can be found here: https://access.redhat.com/solutions/6485391

**Comment by arendej** [comment]
addressed: https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-rosa-cloudwatch-sts.html
