### ISSUE TITLE
GPU Instance Types

### ISSUE THREAD

**Issue by 0kashi** [openshift-cs/managed-openshift#6]
Enable the use of GPU enabled instances for worker nodes.

**Comment by xiaotiancd** [comment]
Hi is there any progress of using GPU on ROSA?

**Comment by mkorejo** [comment]
Any updates or movement here?

As a consultant, I am talking to users in the HPC and ML space about ROSA, and GPU support is something that comes up often. I would love to get an indication around when this might be available.

**Comment by dvasilen** [comment]
Any progress to report regarding GPU support in ROSA?

**Comment by ckyriakidou** [comment]
Any movement at all here?

**Comment by manfredmuth** [comment]
Same here: Any progress?
Customers ask about support of ROSA/ARO GPU out of the box.

**Comment by maulik-modi22** [comment]
Happy new year. 
We are in 2023 now. What's update here?

**Comment by 0kashi** [comment]
Thanks for all the feedback!  We understand the eagerness to use GPU instances and are diligently working on this.  This will be available soon.

**Comment by samueldeklund** [comment]
Is there a timeline for this issue? Is there any more information on what "Coming Soon" means? I would love to use this but my use case would be blocked by not having GPU nodes.

**Comment by maulik-modi22** [comment]
May I know the first OCP version on ROSA that supports GPU instance type support?

**Comment by arendej** [comment]
> May I know the first OCP version on ROSA that supports GPU instance type support?

Any current supported version in the ROSA lifecycle: https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.html#sd-life-cycle-dates_rosa-life-cycle

**Comment by arendej** [comment]
https://cloud.redhat.com/blog/gpu-instance-types-available-for-rosa
