### ISSUE TITLE
AWS instance types: ARM / Gravitons (HCP)

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#73]
Enable the use of AWS instance types Graviton2/3/4, and other ARM64 based CPU architecture types as worker/compute nodes with ROSA HCP.

**Comment by walidshaari** [comment]
Any update on this? and can I check which instance types are supported?

**Comment by AlexonOliveiraRH** [comment]
Any update on this?

**Comment by tohwsw** [comment]
When is this expected?

**Comment by arendej** [comment]
ROSA w/ HCP clusters built new as of July 25th can run Graviton machinepools.
