### ISSUE TITLE
Support SCP enforced EBS encryption upon pre-flight instances

### ISSUE THREAD

**Issue by arendej** [openshift-cs/managed-openshift#82]
Red Hat runs ephemeral instances as part of pre-flight for cluster creation and they should satisfy being encrypted when SCPs enforce encrypted volumes only.

**Comment by acathrow** [comment]
Committed for Q2 2022
In the interim customers can configure automatic EBS encryption
https://aws.amazon.com/premiumsupport/knowledge-center/ebs-automatic-encryption/
