### ISSUE TITLE
Add support for AWS NLB

### ISSUE THREAD

**Issue by acathrow** [openshift-cs/managed-openshift#9]
Add support for AWS Network Load Balancer (NLB) in addition to Classic Load Balancer

**Comment by janvanzoggel** [comment]
My customer would be helped with this feature. The NLB allows the original IP of the consumer to become available in the pod where the ELB classic in TCP modus will always show the internal IP of the ELB. This was discussed with RH support and acknowledged. 

There is a workaround on AWS ELB with this:
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
so it works for now, but it's troublesome for devops teams to always require the platform team so enable this (or allow CLI access to the NLB config or automate it in cicd).

**Comment by thechriswick** [comment]
Are there any updates or estimated deployment timeframes for this?

**Comment by bchandra-ocp** [comment]
https://access.redhat.com/articles/7028653
